FROM ubuntu:18.04

# Update
RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y python3 python3-dev
RUN apt-get install -y python3-pip

RUN pip3 install --upgrade pip


WORKDIR /var/task

COPY requirements.txt /var/task/requirements.txt

ENV PYTHONPATH /var/task/.pypath

RUN \
  mkdir -p .pypath 

RUN \
  pip3 install -r requirements.txt -t .pypath/ 

ADD gams_parser /var/task/.pypath/gams_parser
